config/routes.rb
Rails.application.routes.draw do
  resources :employees
  devise_for :employees
  root "departments#index"
  resources :departments
  resources :departments do
    resources :employees, only: %i[new create update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
class Department < ApplicationRecord
  # validations
  validates :name, presence: true, uniqueness: true
  validates :cover, presence: true

  # Active Storage
  has_one_attached :cover

  # Asociation
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  attr_accessor :skip_password_validation
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validations
  validates :name, :position, :avatar, presence: true

  # Associations
  belongs_to :department, counter_cache: true

  has_many :reports, class_name: "Employee",
                     foreign_key: "manager_id",
                     dependent: :nullify,
                     inverse_of: "manager"

  belongs_to :manager, class_name: "Employee",
                       optional: true

  # ActiveStorage
  has_one_attached :avatar

  private

  def password_required?
    return false if skip_password_validation
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[show edit update destroy]

  # GET /departments
  def index
    @departments = Department.all
  end

  # GET /departments/1
  def show; end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit; end

  # POST /departments
  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to @department, notice: "Department was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /departments/1
  def update
    if @department.update(department_params)
      redirect_to @department, notice: "Department was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /departments/1
  def destroy
    @department.destroy
    redirect_to departments_url, notice: "Department was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name, :description, :employees_count, :cover)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[show edit update destroy]

  # GET /employees/1
  def show; end

  # GET /employees/new
  # GET	/departments/:department_id/employees/new
  def new
    @department = Department.find(params[:department_id])
    @employee = Employee.new
    @departments = Department.all
    @employees = @department.employees
  end

  # GET /employees/1/edit
  def edit
    @department = @employee.department
    @departments = Department.all
    @employees = @department.employees
  end

  # POST /employees
  # POST	/departments/:department_id/employees
  def create
    @department = Department.find(params[:department_id])
    @departments = Department.all
    @employees = @department.employees

    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to @employee.department, notice: "Employee was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /departments/:department_id/employees/:id
  def update
    @department = @employee.department
    @departments = Department.all
    @employees = @department.employees

    @employee.skip_password_validation = true

    if @employee.update(employee_params)
      redirect_to @employee.department, notice: "Employee was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /employees/1
  def destroy
    @employee.destroy
    redirect_to @employee.department, notice: "Employee was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def employee_params
    params.require(:employee).permit(:name, :nationality, :email, :position, :birth_date,
                                     :department_id, :manager_id, :avatar, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(record, attribute)
    errors = record.errors.full_messages_for(attribute).map do |message|
      content_tag(:span, message, class: "input__error-message")
    end

    safe_join(errors)
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>" class="department-card">
  <%=image_tag department.cover, class: "department-card__image"%>
  <div>
    <div class="department-card__content">
      <%=link_to content_tag("p", department.name, class: "heading--sm"), department_path(department)%>
      <p class="content--sm"><%=department.employees_count%> employees</p>
    </div>
    <div class="department-card__actions">
      <%=link_to image_tag("icons/pencil.svg"), 
                 edit_department_path(department), 
                 class: "action-icon"%>

      <%=button_to image_tag("icons/trash.svg"), 
                   department_path(department), 
                   method: :delete, data: { turbo: "false" },
                   class: "action-icon"%>
    </div>
  </div>
</div>

app/views/departments/_form.html.erb
<%= form_with(model: department, class: "flex flex-column gap-4") do |form| %>
  <div class="input">
    <%= form.label :name, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.text_field :name, class: "input__content", placeholder: "Secret planning", autofocus: true %>
    </div>
    <%=errors_for(department, :name)%>
  </div>

  <div class="input">
    <%= form.label :description, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.text_area :description, class: "input__content", placeholder: "This is the best department yet..."%>
    </div>
    <%=errors_for(department, :description)%>
  </div>

  <div class="input">
    <%= form.label :cover, class:"content-xs overline"%>

    <%=image_tag(department.cover, class: "department-card__image") if department.cover.attached?%>

    <%= form.file_field :cover, class: "input__content"%>

    <%=errors_for(department, :cover)%>
  </div>

  <div>
    <%= form.submit class: "button button--secondary full-width" %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<div class="flex flex-column gap-4">
  <h1>Editing department</h1>

  <%= render "form", department: @department %>

  <%= link_to "Back", departments_path, class: "button button--subtle" %>
</div>

app/views/departments/index.html.erb
<section class="section">
  <div>
    <div class="flex flex-column gap-4">
      <h1 class="heading">Departments</h1>

      <%=link_to "New Department", new_department_path, class: "button button--secondary button--sm fit-content"%>
      
      <div id="departments" class="flex flex-column gap-8">
        <% @departments.each do |department| %>
          <%= render department %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/departments/new.html.erb
<div class="flex flex-column gap-4">
  <h1 class="heading">New department</h1>

  <%= render "form", { department: @department } %>

  <%= link_to "Back", departments_path, class: "button button--subtle" %>

</div>

app/views/departments/show.html.erb
<div class="flex flex-column gap-4">
  <h1 class="heading"><%=@department.name%></h1>
  <p><%=@department.description%></p>
  <%=link_to "New Employee", new_department_employee_path(@department), class: "button button--secondary button--sm fit-content"%>
  <%@department.employees.each do |employee|%>
    <%=render employee%>
  <%end%>
</div>

app/views/employees/_employee.html.erb
<div class="employee-card">
  <div class="employee-card__content">
    <%=image_tag employee.avatar, class: "employee-card__image"%>
    <div class="employee-card__data">
      <%=link_to content_tag("p", employee.name), employee_path(employee), class: "heading--xs"%>
      <p class="content-sm"><%=employee.position%></p>
    </div>
  </div>
  <div class="employee-card__actions">
    <%=link_to image_tag("icons/pencil.svg"), 
                edit_employee_path(employee), 
                class: "action-icon"%>
    <%=button_to image_tag("icons/trash.svg"), 
                  employee_path(employee), 
                  method: :delete, "data-turbo": "false",
                  class: "action-icon"%>
  </div>
</div>

app/views/employees/_form.html.erb
<%= form_with(model: [department, employee], class: "flex flex-column gap-4", data: { turbo: "false" }) do |form| %>
  <div class="input">
    <%= form.label :name, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.text_field :name, class: "input__content", placeholder: "John Doe", autofocus: true %>
    </div>
    <%=errors_for(employee, :name)%>
  </div>

  <div class="input">
    <%= form.label :nationality, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.text_field :nationality, class: "input__content", placeholder: "Peru" %>
    </div>
    <%=errors_for(employee, :nationality)%>
  </div>

  <div class="input">
    <%= form.label :email, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.email_field :email, class: "input__content", placeholder: "example@mail.com" %>
    </div>
    <%=errors_for(employee, :email)%>
  </div>

  <div class="input">
    <%= form.label :position, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.text_field :position, class: "input__content", placeholder: "eternal apprentice" %>
    </div>
    <%=errors_for(employee, :position)%>
  </div>

  <div class="input">
    <%= form.label :birth_date, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.date_field :birth_date, class: "input__content" %>
    </div>
    <%=errors_for(employee, :birth_date)%>
  </div>

  <div class="select">
    <%= form.label :department_id, class:"content-xs overline"%>
    <%= form.collection_select :department_id, departments, :id, :name, { prompt: true, selected: department.id }, { class: "select__input" } %>
    <%=errors_for(employee, :department_id)%>
  </div>

  <%# <select name="department_id" id="department_id">
    <option value="">Select one</option>
    <option value="1">Engineering</option>
    <option value="2">marketing</option>
    <option value="3">Operations</option>
  </select> %>

  <div class="select">
    <%= form.label :manager_id, class:"content-xs overline"%>
    <%= form.collection_select :manager_id, employees, :id, :name, { include_blank: "No Manager" }, { class: "select__input" } %>
    <%=errors_for(employee, :manager_id)%>
  </div>

  <div class="input">
    <%= form.label :avatar, class:"content-xs overline"%>
    <%= form.file_field :avatar, class: "input__content"%>
    <%=errors_for(employee, :avatar)%>
  </div>

  <div class="input">
    <%= form.label :password, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.password_field :password, class: "input__content", placeholder: "******" %>
    </div>
    <%=errors_for(employee, :password)%>
  </div>

  <div class="input">
    <%= form.label :password_confirmation, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.password_field :password_confirmation, class: "input__content", placeholder: "******" %>
    </div>
    <%=errors_for(employee, :password_confirmation)%>
  </div>

  <div>
    <%= form.submit class: "button button--secondary full-width" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="flex flex-column gap-4">
  <h1 class="heading">Edit Employee</h1>

  <%= render "form", department: @department, employee: @employee, departments: @departments, employees: @employees %>
  <%= link_to "Back", department_path(@department), class: "button button--subtle" %>

</div>

app/views/employees/new.html.erb
<div class="flex flex-column gap-4">
  <h1 class="heading">New Employee</h1>

  <%= render "form", department: @department, employee: @employee, departments: @departments, employees: @employees %>
  <%= link_to "Back", department_path(@department), class: "button button--subtle" %>

</div>

app/views/employees/show.html.erb
<div class="flex flex-column gap-2 items-center mb-4">
  <%=image_tag(@employee.avatar, class: "employee-card__image")%>
  <p class="heading--sm"><%=@employee.name%></p>
  <p><%=@employee.position%></p>
  <p><%=@employee.department.name%></p>
  <p><%=@employee.nationality%></p>
  <p><%=@employee.birth_date%></p>
  <div class="flex gap-2">
    <%=link_to image_tag("icons/pencil.svg"), 
                edit_employee_path(@employee), 
                class: "action-icon"%>
    <%=button_to image_tag("icons/trash.svg"), 
                  employee_path(@employee), 
                  method: :delete, "data-turbo": "false",
                  class: "action-icon"%>
  </div>
</div>

<div class="flex flex-column gap-8">
  <h2 class="heading--xs">Manager</h2>
  <%if @employee.manager%>
    <%=render @employee.manager%>
  <%else%>
    <p>No manager</p>
  <%end%>

  <h2 class="heading--xs">Reports</h2>
  <%@employee.reports.each do |employee|%>
    <%=render employee%>
  <%end%>
  <%if @employee.reports.empty?%>
    <p>No reports</p>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Offix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header class="header">
      <div class="container navbar">
        <%=link_to image_tag("/images/offix-logo.png"), root_path, class: "logo"%>
        <nav>
          <ul class="navbar-links" role="list">
            <li>Welcome user</li>
            <li><%=link_to "Profile", "#"%></li>
            <li><%=link_to "Search", "#"%></li>
            <li>
                <%=button_to "Log Out", "#"%>
            </li>
          </ul>
        </nav>
        <div class="js-navbar-menu">
          <%=image_tag "icons/menu.svg", class: "navbar__menu-icon"%>
          <%=image_tag "icons/close.svg", class: "navbar__menu-icon-close"%>
        </div>
      </div>
    </header>

    <main>
      <section>
        <p style="color: green"><%= notice %></p>
        <p style="color: red"><%= alert%></p>
        <%= yield %>
      </section>
    </main>
    
  <footer class="footer bg-gray-100">
      <p>© 2022 - Offix</p>
  </footer>

  <script>
    const navbarMenu = document.querySelector(".js-navbar-menu");
    const navbar = document.querySelector(".navbar");
    navbarMenu.addEventListener("click", () => navbar.classList.toggle("navbar--open"));
  </script>
  </body>
</html>